### ISSUE TITLE
Use a Wallet library

### ISSUE THREAD

**Issue by josepablofm78** [keyko-io/filecoin-verifier-frontend#2]
The front end application have to allow the use of wallets to guard filecoin accounts.  This could be done using some already implemented libraries, whether Filecoin implementation or others

- [x] Research about filecoin wallet libraries #5 
- [x] Research alternatives to Filecoin's Wallets #6 
- [x] Integrate Wallet Library #7
